version: "3.3"
services:
  web:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
