export default {
  SUCCESSFUL_LOGIN: "SUCCESSFUL_LOGIN",
  PERFORM_LOGOUT: "PERFORM_LOGOUT",
  LOAD_INTERNET_USER: "LOAD_INTERNET_USER",
  FILL_LANGUAGES: "FILL_LANGUAGES",
  LOADING: "LOADING",
  UPDATE_INTERNET_USER: "UPDATE_INTERNET_USER",
  LOAD_PACKAGES: "FILL_PACKAGES",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
};
